sudo: required
language: bash

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script:
  - echo "test"